{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elabftw.secretName" . }}
  labels:
    {{- include "elabftw.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  {{- if .Values.secrets.secretKey }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  {{- end }}
  {{- if .Values.secrets.redisPassword }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.awsAccessKey }}
  ELAB_AWS_ACCESS_KEY: {{ .Values.secrets.awsAccessKey | quote }}
  {{- end }}
  {{- if .Values.secrets.awsSecretKey }}
  ELAB_AWS_SECRET_KEY: {{ .Values.secrets.awsSecretKey | quote }}
  {{- end }}
  {{- if .Values.secrets.statusPassword }}
  STATUS_PASSWORD: {{ .Values.secrets.statusPassword | quote }}
  {{- end }}
{{- end }}
