apiVersion: v1
kind: Service
metadata:
  name: {{ include "elabftw.fullname" . }}
  labels:
    {{- include "elabftw.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "elabftw.web.selectorLabels" . | nindent 4 }}
